[workspace]
members = ["carcara", "cli", "test-generator"]
resolver = "2"

[profile.release]
debug = 1
incremental = true

[profile.release-lto]
inherits = "release"
debug = 0
incremental = false
lto = true