use crate::ast::{
    AnchorArg, Binder, Constant, Operator, ProblemPrelude, Proof as ProofElaborated, ProofCommand,
    ProofIter,
    ProofStep as AstProofStep, Rc, Sort, Subproof, Term as AletheTerm, polyeq,
    pool::{self, PrimitivePool, TermPool},
};
use indexmap::IndexMap;
use itertools::Itertools;
use thiserror::Error;
use try_match::unwrap_match;

use std::{
    collections::HashSet,
    ops::Deref,
    time::Duration,
    vec,
};

pub mod goal;
pub mod logic;
#[macro_use]
pub mod syntax;

pub mod rules;

use logic::Features;
use rules::{get_premises_clause, unary_clause_to_prf};
use syntax::*;

#[derive(Debug, Error)]
pub enum TranslatorError {
    #[error("the pivot is not in the clause")]
    PivotNotInClause,
    #[error("the premises are incorrect")]
    PremisesError,
    #[error("rule `{0}` is not supported by the Lambdapi backend")]
    UnsupportedRule(String),
}

pub type TradResult<T> = Result<T, TranslatorError>;

#[derive(Default)]
pub struct Config {
    pub no_elab: bool,
    pub why3: bool,
    /// Emit `admit` for rules the backend does not implement instead of
    /// failing with [`TranslatorError::UnsupportedRule`].
    pub admit_unsupported: bool,
}

#[derive(Default)]
pub struct Context {
    prelude: Vec<Command>,
    /// Sharing map contains all the dagify common sub expression generated by the SMT-solver
    /// with the `:named` annotation. This feature make step more compact and easier to debug.
    /// We do not propose an option to disable this feature because it is enough to run Carcara translation
    /// by providing a proof file without `:named` annotation.
    pub term_indices: IndexMap<Rc<AletheTerm>, (usize, String)>,
    pub term_sharing: IndexMap<Rc<AletheTerm>, (String, Term)>,

    pub global_variables: HashSet<Rc<AletheTerm>>,
}

impl Context {
    /// Convert dagify subexpression into `Term::TermId` otherwise just apply a canonical conversion
    fn get_or_convert(&self, term: &Rc<AletheTerm>) -> (Term, HashSet<String>) {
        term::conv(term, self)
    }
}


fn translate_sort_function(sort: &Sort, used: &mut Features) -> Term {
    match sort {
        Sort::Bool => omicron(),
        Sort::Int => {
            // `int` is `Stdlib.Z.int`, and `Stdlib.Z` reaches a generated proof
            // only through `alethe.lia`. Naming the sort is therefore as much of a
            // dependency on the integer layer as using a `la_*` rule is.
            *used |= Features::INT;
            "int".into()
        }
        Sort::Function(params) => {
            let sorts = params
                .iter()
                .map(|s| translate_sort_function(s, used))
                .collect_vec();

            sorts
                .into_iter()
                .reduce(|acc, e| Term::Sort(BuiltinSort::Arrow(Box::new(acc), Box::new(e))))
                .unwrap()
        }
        Sort::Atom(a, args) => {
            if args.is_empty() {
                a.as_ref().into()
            } else {
                let mut args: Vec<Term> = args
                    .iter()
                    .map(|s| translate_sort_function(s, used))
                    .collect_vec();
                let mut sort = vec![a.as_ref().into()];
                sort.append(&mut args);
                Term::Terms(sort)
            }
        }
        ref e => unreachable!("{:?}", e),
    }
}

/// Translate the SMT declaration symbol of sort and function into Lambdapi symbol.
/// The type Prop is used a default to be polymorphic.
/// ex:
/// (declare-sort S 0)
/// become
/// symbol S: Prop;
fn translate_prelude(prelude: ProblemPrelude, used: &mut Features) -> Vec<Command> {
    let mut sort_declarations_symbols = prelude
        .sort_declarations
        .into_iter()
        .map(|(id, arity)| {
            let sorts = itertools::repeat_n(set(), arity + 1).collect_vec();
            Command::Definition(id, vec![], Some(Term::Function(sorts)), None)
        })
        .collect::<Vec<Command>>();

    let mut function_declarations_symbols = prelude
        .function_declarations
        .into_iter()
        .map(|(id, sort)| {
            let sort = tau(translate_sort_function(&sort, used));

            Command::Definition(id, vec![], Some(sort), None)
        })
        .collect::<Vec<Command>>();

    sort_declarations_symbols.append(&mut function_declarations_symbols);

    sort_declarations_symbols
}


/// Does the proof name an integer anywhere?
///
/// An integer literal is emitted as `Stdlib.Z.<n>`, and `Stdlib.Z` is required by a
/// generated proof only through `alethe.lia`. Gating that module on the `la_*` and
/// `arith-*` rules alone is not enough: a proof can carry an integer constant --
/// `(step t1 (cl (= 1 1)) :rule refl)` -- without ever reaching an arithmetic rule,
/// and would then print a numeral no module in its header can scope.
///
/// Sorts are handled separately, in `translate_sort_function`.
fn integers_used(proof: &ProofElaborated) -> bool {
    fn in_term(term: &Rc<AletheTerm>, seen: &mut HashSet<*const AletheTerm>) -> bool {
        if !seen.insert(Rc::as_ptr(term)) {
            return false;
        }
        let any = |ts: &[Rc<AletheTerm>], seen: &mut _| ts.iter().any(|t| in_term(t, seen));
        match term.deref() {
            AletheTerm::Const(Constant::Integer(_)) => true,
            AletheTerm::Const(_) => false,
            AletheTerm::Var(_, sort) => matches!(sort.deref(), Sort::Int),
            AletheTerm::App(f, args) => in_term(f, seen) || any(args, seen),
            AletheTerm::Op(_, args) | AletheTerm::AsOp(_, _, args) => any(args, seen),
            AletheTerm::Binder(_, bs, t) => {
                bs.iter().any(|(_, sort)| matches!(sort.deref(), Sort::Int)) || in_term(t, seen)
            }
            AletheTerm::Let(bs, t) => bs.iter().any(|(_, v)| in_term(v, seen)) || in_term(t, seen),
            AletheTerm::Match(t, cases) => {
                in_term(t, seen) || cases.iter().any(|c| in_term(&c.body, seen))
            }
            AletheTerm::ParamOp { op_args, args, .. } => any(op_args, seen) || any(args, seen),
        }
    }

    fn in_commands(cs: &[ProofCommand], seen: &mut HashSet<*const AletheTerm>) -> bool {
        cs.iter().any(|c| match c {
            ProofCommand::Assume { term, .. } => in_term(term, seen),
            // Only the clause. A step's `:args` are not all terms: for `and`,
            // `not_or`, `and_pos` and `or_neg` they are clause and conjunct
            // indices, which arrive as `Constant::Integer` but are emitted as
            // `Stdlib.Nat.n` and say nothing about ℤ. Counting them put `lia`
            // -- and its admits -- into pure QF_UF proofs. The args that really
            // are integer terms belong to `la_generic`, which reports `INT`
            // itself; anything instantiated into a formula shows up in a clause.
            ProofCommand::Step(s) => s.clause.iter().any(|t| in_term(t, seen)),
            ProofCommand::Subproof(sp) => {
                let args = sp.args.iter().any(|a| match a {
                    AnchorArg::Variable((_, sort)) => matches!(sort.deref(), Sort::Int),
                    AnchorArg::Assign(_, t) => in_term(t, seen),
                });
                args || in_commands(&sp.commands, seen)
            }
        })
    }

    let mut seen = HashSet::new();
    proof
        .constant_definitions
        .iter()
        .any(|(_, t)| in_term(t, &mut seen))
        || in_commands(&proof.commands, &mut seen)
}

fn gen_shared_term(ctx: &Context) -> Vec<Command> {
    ctx.term_indices
        .iter()
        .filter(|(_, (counter, _))| *counter >= 2)
        .map(|(t, (..))| ctx.term_sharing[t].clone())
        .map(|(id, term)| Command::Definition(id, vec![], None, Some(term)))
        .collect_vec()
}

pub fn produce_lambdapi_proof(
    prelude: ProblemPrelude,
    proof_elaborated: ProofElaborated,
    mut pool: pool::PrimitivePool,
    config: Config,
) -> TradResult<ProofFile> {
    let mut proof_file = ProofFile::new();
    let logic = prelude.logic.clone();

    let global_variables: HashSet<_> = prelude
        .function_declarations
        .iter()
        .map(|var| pool.add(var.clone().into()))
        .collect();

    let (declared, kind) = logic::features_of_logic(logic.as_deref());
    // What the *steps* turn out to need, accumulated as they are translated. It
    // must start empty rather than from `declared`: an unrecognised logic
    // declares every feature, and seeding it here would make `used` report the
    // real carrier as needed on that basis alone, which is precisely what
    // `logic::modules` gates `alethe.lra` against.
    let mut features = Features::EMPTY;

    if integers_used(&proof_elaborated) {
        features |= Features::INT;
    }

    proof_file.definitions = translate_prelude(prelude, &mut features);

    let mut context = Context {
        global_variables,
        ..Default::default()
    };

    let mut commands = translate_commands(
        &mut context,
        &mut proof_elaborated.iter(),
        &mut pool,
        &config,
        &mut features,
        |id, t, ps| {
            let modifier = ps.is_some().then_some(Modifier::Opaque);
            Command::Symbol(modifier, normalize_name(id), vec![], t, ps.map(Proof))
        },
    )?;

    // Stop postulating the problem's last assertion and end on what the proof is
    // actually for. Leaves `commands` alone, and the file ending at `π̇ □`, when the
    // proof has no top-level assume or does not close the empty clause.
    goal::discharge(&mut commands, &proof_elaborated, &context);

    let shared_terms = gen_shared_term(&context);

    proof_file.definitions.extend(shared_terms);

    proof_file.content.extend(commands);

    report_logic(logic.as_deref(), declared, features, kind);
    proof_file.requires = logic::modules(features)
        .into_iter()
        .map(|m| Command::RequireOpen(m.to_owned()))
        .collect();

    Ok(proof_file)
}






#[inline]
/// Lambdapi does not support symbol name containing dot so
/// they are replace by underscore.
/// SMTLIB quoted symbols `|x|` allow to have pretty much any character in a symbol.
/// However that is incompatible with identifier of Lambdapi.
fn normalize_name<S: AsRef<str>>(name: S) -> String {
    // call as_ref() to get a &str
    name.as_ref()
        .replace(".", "_")
        .replace(printer::WHITE_SPACE, "")
        .replace("$", "")
}

/// Translate (anchor :step ti) and its steps
/// A subproof is translated into an opaque symbol
/// added to the prelude of the file.
fn translate_subproof<'a>(
    context: &mut Context,
    iter: &mut ProofIter<'a>,
    commands: &[ProofCommand],
    assignment_args: Vec<(&(String, Rc<Sort>), &Rc<AletheTerm>)>,
    pool: &mut PrimitivePool,
    config: &Config,
    features: &mut Features,
) -> TradResult<(String, Vec<Term>, Vec<ProofStep>)> {
    let subproof = commands.last().unwrap();

    //Get the last step of the proof
    let (id, clause, rule) = unwrap_match!(
        subproof,
        ProofCommand::Step(AstProofStep { id, clause, rule,.. }) => (normalize_name(id), clause, rule)
    );

    let clause = clause
        .iter()
        .map(|t| context.get_or_convert(t).0)
        .collect_vec();

    let mut fresh_ctx = Context {
        global_variables: context.global_variables.clone(),
        term_indices: context.term_indices.clone(),
        term_sharing: context.term_sharing.clone(),
        ..Default::default()
    };

    let mut proof_cmds = translate_commands(&mut fresh_ctx, iter, pool, config, features, |id, t, ps| {
        ProofStep::Have(normalize_name(id), t, ps.unwrap_or(admit()))
    })?;

    proof_cmds
        .iter_mut()
        .filter(|cmd| matches!(cmd, ProofStep::Have(_, _, _)))
        .for_each(|cmd| {
            if let ProofStep::Have(name, cl, steps) = cmd {
                cl.visit(&assignment_args);
                *cmd = ProofStep::Have((*name).clone(), cl.clone(), steps.clone());
            }
        });

    let assignment_args = assignment_args
        .into_iter()
        .map(|(_, term)| Term::from(term))
        .collect_vec();

    //TODO: Remove this side effect by append the prelude in translate_commands and return the  pair Subproof + Axioms in subproof
    context.prelude.append(&mut fresh_ctx.prelude); // Add subproof of current subproof to the prelude

    let subproof_have_wrapper = if rule == "bind" {
        let mut proof = vec![];

        let last_step_id = unwrap_match!(commands.get(commands.len() - 2), Some(ProofCommand::Step(AstProofStep{id, ..})) => normalize_name(id));

        let bind_lemma = match subproof.clause().first().expect("clause is empty").deref() {
            AletheTerm::Op(Operator::Equals, args)
                if matches!(args[0].deref(), AletheTerm::Binder(Binder::Forall, _, _))
                    && matches!(args[1].deref(), AletheTerm::Binder(Binder::Forall, _, _)) =>
            {
                "bind_∀"
            }
            AletheTerm::Op(Operator::Equals, args)
                if matches!(args[0].deref(), AletheTerm::Binder(Binder::Exists, _, _))
                    && matches!(args[1].deref(), AletheTerm::Binder(Binder::Exists, _, _)) =>
            {
                "bind_∃"
            }
            _ => unreachable!(),
        };

        // `bind_∀` / `bind_∃` live in `quant.lp`. This wrapper is built here rather
        // than through the rule dispatch table, which reports no feature for
        // `bind`, so the dependency has to be recorded at the point of use.
        *features |= Features::QUANT;

        proof.push(ProofStep::Apply(Term::from("∨ᵢ₁"), SubProofs(None)));
        assignment_args.into_iter().for_each(|term| {
            proof.push(ProofStep::Apply(Term::from(bind_lemma), SubProofs(None)));
            proof.push(ProofStep::Assume(vec![format!("{}", term)]));
        });
        proof.append(&mut proof_cmds);

        proof.push(ProofStep::Apply(
            terms![Term::from("π̇ₗ"), Term::from(last_step_id)],
            SubProofs(None),
        ));

        proof
    } else if rule == "sko_forall" {
        let last_step_id = unwrap_match!(commands.last(), Some(ProofCommand::Step(AstProofStep{id, ..})) => normalize_name(id));

        // end of the script
        proof_cmds.append(&mut lambdapi! {
            apply "∨ᵢ₁";
            apply "π̇ₗ" (@last_step_id.into());
        });
        proof_cmds
    } else {
        proof_cmds
    };

    context.term_indices.extend(fresh_ctx.term_indices);
    context.term_sharing.extend(fresh_ctx.term_sharing);

    Ok((id, clause, subproof_have_wrapper))
}



fn translate_commands<'a, F, T>(
    ctx: &mut Context,
    proof_iter: &mut ProofIter<'a>,
    pool: &mut PrimitivePool,
    config: &Config,
    features: &mut Features,
    f: F,
) -> TradResult<Vec<T>>
where
    F: Fn(String, Term, Option<Vec<ProofStep>>) -> T,
{
    let mut proof_steps = Vec::new();

    while let Some(command) = proof_iter.next() {
        let clause = command.clause();
        clause.iter().for_each(|c| c.visit(ctx, pool));

        match command {
            ProofCommand::Assume { id, term } => proof_steps.push(f(
                id.into(),
                term::clauses(vec![ctx.get_or_convert(term).0]),
                None,
            )),
            ProofCommand::Step(AstProofStep {
                id, clause, premises, rule, args, ..
            }) => {
                let (script, used) = rules::translate_step(
                    ctx, proof_iter, pool, clause, premises, rule, args, config,
                )?;
                *features |= used;

                let terms = clause
                    .iter()
                    .map(|term| ctx.get_or_convert(term).0)
                    .collect();

                if let Some(script) = script {
                    proof_steps.push(f(
                        normalize_name(id),
                        Term::Alethe(LTerm::Proof(Box::new(Term::Alethe(LTerm::Clauses(terms))))),
                        Some(script),
                    ));
                }

                // Iteration is flattened by the ProofIter, so the loop must stop at the
                // last step of a subproof: the Subproof arm recurses into it.
                if proof_iter.is_end_step() {
                    break;
                }
            }
            ProofCommand::Subproof(Subproof { commands, args, .. }) => {
                let (_id, clause, subproof) = translate_subproof(
                    ctx,
                    proof_iter,
                    commands.as_slice(),
                    args.iter()
                        .filter(|a| matches!(a, AnchorArg::Assign(_, _)))
                        .map(|a| unwrap_match!(a, AnchorArg::Assign(s, t) => (s, t)))
                        .collect_vec(),
                    pool,
                    config,
                    features,
                )?;

                let sub = commands.last().unwrap();

                //Get the last step of the proof
                let (id, cl, rule) = unwrap_match!(
                    sub,
                    ProofCommand::Step(AstProofStep { id, clause, rule,.. }) => (normalize_name(id), clause, rule)
                );

                if rule.contains("subproof") {
                    //HACK: we convert all the Have proof step into symbols to improve lambdapi check performance.
                    // We only do this for proof that use the `subproof` rule because `bind` and `sko_forall` for example
                    // creates temporary free variable in their context making the split of steps into `symbol` instead of `have` impossible.
                    // Lambdapi seems to be very slow on proof that have a large context.
                    let res = subproof.into_iter().map(|s| unwrap_match!(s, ProofStep::Have(id, r#type, proof) =>  f(id, r#type, Some(proof)))).collect_vec();
                    proof_steps.extend(res);

                    let discharge = unwrap_match!(commands.last(), Some(ProofCommand::Step(AstProofStep{id: _, clause:_, rule:_, premises:_, args:_, discharge})) => discharge);

                    let premises_discharge = get_premises_clause(proof_iter, discharge);

                    let mut script = std::iter::repeat_n(
                        ProofStep::Apply(Term::TermId("∨ᵢ₂".to_owned()), SubProofs(None)),
                        premises_discharge.len(),
                    )
                    .collect_vec();

                    let (psy_id, trailing_false_on_last_step) = unwrap_match!(commands.get(commands.len() - 2), Some(ProofCommand::Step(AstProofStep{id, clause, ..})) => {
                        (normalize_name(id), clause.iter().last().is_some_and(|t| t.is_bool_false()))
                    });

                    let trailing_false_on_conclusion_clause =
                        cl.iter().last().is_some_and(|t| t.is_bool_false());

                    // Some subproof can add a trailing false in their clause and also for the step just before the clonclusion of the subproof.
                    // We detect if there is a trailing false if the number of the element in the clause and the discharge are different
                    if trailing_false_on_conclusion_clause && trailing_false_on_last_step {
                        script.push(ProofStep::Apply(psy_id.as_str().into(), SubProofs(None)));
                    } else if trailing_false_on_conclusion_clause {
                        // Case with a trailing false
                        script.push(ProofStep::Apply(
                            Term::TermId("∨ᵢ₂".to_owned()),
                            SubProofs(None),
                        ));
                        script.push(ProofStep::Apply(psy_id.as_str().into(), SubProofs(None)));
                    } else if trailing_false_on_last_step {
                        // Case with a trailing false
                        script.push(ProofStep::Apply(
                            Term::TermId("∨ᵢ₁".to_owned()),
                            SubProofs(None),
                        ));
                        script.push(ProofStep::Apply(
                            unary_clause_to_prf(psy_id.as_str()),
                            SubProofs(None),
                        ));
                    } else {
                        // Case without a trailing false
                        script.push(ProofStep::Apply(
                            Term::TermId("∨ᵢ₁".to_owned()),
                            SubProofs(None),
                        ));

                        script.push(ProofStep::Apply(
                            unary_clause_to_prf(psy_id.as_str()),
                            SubProofs(None),
                        ));
                    }

                    proof_steps.push(f(
                        normalize_name(id),
                        Term::Alethe(LTerm::Proof(Box::new(Term::Alethe(LTerm::Clauses(clause))))),
                        Some(script),
                    ));
                } else {
                    proof_steps.push(f(
                        normalize_name(id),
                        Term::Alethe(LTerm::Proof(Box::new(Term::Alethe(LTerm::Clauses(clause))))),
                        Some(subproof),
                    ));
                }
            }
        };
    }

    Ok(proof_steps)
}

#[cfg(test)]
mod tests_translation {
    use super::test_macros::parse_test_instance;
    use super::*;

    #[test]
    fn test_resolution() {
        let problem = "
           (declare-fun a () Bool)
            (declare-fun b () Bool)
            (declare-fun c () Bool)
        ";
        let proof = "
            (assume a4 (not (= a a)))
            (step t1 (cl (= a a) (= b b)) :rule hole)
            (step t2 (cl (= c c) (not (= a a))) :rule hole)
            (step t3 (cl (= b b) (= c c)) :rule resolution :premises (t1 t2) :args ((= a a) true))
        ";
        let (problem, proof, _, mut pool) = parse_test_instance(problem, proof).unwrap();

        let global_variables: HashSet<_> = problem
            .prelude
            .function_declarations
            .iter()
            .map(|var| pool.add(var.clone().into()))
            .collect();

        let mut ctx = Context {
            global_variables,
            ..Default::default()
        };

        let res = translate_commands(&mut ctx, &mut proof.iter(), &mut pool, &Config::default(), &mut Features::EMPTY, |id, t, ps| {
            let modifier = ps.is_some().then_some(Modifier::Opaque);
            Command::Symbol(modifier, normalize_name(id), vec![], t, ps.map(Proof))
        })
        .expect("translate trans");

        let _: Command = res.last().unwrap().clone();

        //println!("{}", t3);
    }

    /// The `require` header for a proof whose `(set-logic …)` is not one of the
    /// 25 standard names.
    ///
    /// `logic::modules` gates `alethe.lra` on what the proof *used*, because
    /// `lia` and `lra` rebind the decimal notation to different carriers and a
    /// header carrying both leaves every numeral ambiguous. That guard is only
    /// as good as the value it is handed: seeding the used set from the
    /// declared one made it vacuous, since an unrecognised logic declares every
    /// feature. `logic.rs` covers `modules` in isolation, so only a test at this
    /// level catches the seeding.
    fn requires_of(problem: &str, proof: &str) -> Vec<String> {
        let (problem, proof, _, pool) = parse_test_instance(problem, proof).unwrap();
        let elaborated = ProofElaborated {
            constant_definitions: proof.constant_definitions.clone(),
            commands: proof.commands.clone(),
            filename: proof.filename.clone(),
        };
        produce_lambdapi_proof(problem.prelude, elaborated, pool, Config::default())
            .expect("translation failed")
            .requires
            .iter()
            .map(|c| match c {
                Command::RequireOpen(m) => m.clone(),
                other => panic!("not a require: {other:?}"),
            })
            .collect()
    }

    #[test]
    fn an_unrecognised_logic_does_not_open_the_rational_carrier() {
        // `UF` is not among the 25 standard logics, and this problem has no
        // real arithmetic anywhere -- only an uninterpreted sort.
        let requires = requires_of(
            "(set-logic UF)
             (declare-sort U 0)
             (declare-fun p (U) Bool)
             (declare-fun a () U)",
            "(assume h1 (p a))
             (step t1 (cl (p a)) :rule hole :premises (h1))",
        );
        assert!(
            !requires.iter().any(|m| m == "alethe.lra"),
            "unrecognised logic dragged in the rational carrier: {requires:?}"
        );
        assert!(
            !(requires.iter().any(|m| m == "alethe.lia")
                && requires.iter().any(|m| m == "alethe.lra")),
            "lia and lra must not be opened together: {requires:?}"
        );
    }

    /// An integer literal alone has to pull in the integer layer.
    ///
    /// `Stdlib.Z.<n>` -- and the `int` sort name -- resolve only if the file
    /// required `Stdlib.Z`, which a generated proof reaches only through
    /// `alethe.lia`. Gating that on the `la_*`/`arith-*` rules leaves a proof that
    /// mentions an integer without ever taking an arithmetic step printing a
    /// numeral no module in its header can scope.
    #[test]
    fn an_integer_literal_opens_the_integer_layer() {
        let requires = requires_of(
            "(set-logic QF_UF)
             (declare-fun p (Int) Bool)
             (declare-fun a () Int)",
            "(assume h1 (p a))
             (step t1 (cl (= 1 1)) :rule refl)",
        );
        assert!(
            requires.iter().any(|m| m == "alethe.lia"),
            "an integer literal did not open the integer layer: {requires:?}"
        );
    }

    fn content_of(problem: &str, proof: &str) -> Vec<Command> {
        let (problem, proof, _, pool) = parse_test_instance(problem, proof).unwrap();
        let elaborated = ProofElaborated {
            constant_definitions: proof.constant_definitions.clone(),
            commands: proof.commands.clone(),
            filename: proof.filename.clone(),
        };
        produce_lambdapi_proof(problem.prelude, elaborated, pool, Config::default())
            .expect("translation failed")
            .content
    }

    /// The refutation's last assertion is discharged, not postulated.
    ///
    /// Emitting every `assume` as an axiom makes the axiom set inconsistent by
    /// construction -- the negated goal is among them -- so a concluding `π G` read
    /// off the empty clause would prove nothing. The last assertion has to stop
    /// being an axiom for the final statement to mean anything.
    #[test]
    fn the_last_assertion_is_discharged_not_postulated() {
        let content = content_of(
            "(set-logic QF_UF)
             (declare-fun p () Bool)",
            "(assume h1 p)
             (assume h2 (not p))
             (step t1 (cl) :rule resolution :premises (h1 h2) :args (p true))",
        );

        assert!(
            !content.iter().any(
                |c| matches!(c, Command::Symbol(_, name, _, _, None) if name == "h2")
            ),
            "the discharged assertion is still an axiom: {content:?}"
        );
        // `h1` is not the last assertion, so it stays a hypothesis of the theory.
        assert!(
            content
                .iter()
                .any(|c| matches!(c, Command::Symbol(_, name, _, _, None) if name == "h1")),
            "an assertion other than the last one was discharged: {content:?}"
        );

        // `(not p)` is a negation, so the theorem states `p` itself rather than
        // `¬ (¬ p)`, and it is named after the assertion it discharges.
        let Some(Command::Symbol(_, name, _, statement, Some(_))) = content.last() else {
            panic!("the file does not end in a proved symbol: {content:?}");
        };
        assert_eq!(name, "h2");
        assert_eq!(
            *statement,
            Term::Alethe(LTerm::ClassicProof(Box::new(Term::from("p")))),
            "expected `π p`, got {statement:?}"
        );
    }

    /// A proof that does not close the empty clause is left exactly as it was.
    #[test]
    fn a_proof_that_is_not_a_refutation_keeps_its_axioms() {
        let content = content_of(
            "(set-logic QF_UF)
             (declare-fun p () Bool)",
            "(assume h1 p)
             (step t1 (cl p) :rule hole :premises (h1))",
        );
        assert!(
            content
                .iter()
                .any(|c| matches!(c, Command::Symbol(_, name, _, _, None) if name == "h1")),
            "a non-refutation had its assumption discharged: {content:?}"
        );
    }
}

/// Report how the declared logic compares with what the proof actually used.
///
/// The declared logic is an over-approximation by construction (the standard
/// has no name for every feature combination), so an unused declared feature is
/// normal. The interesting direction is the other one: a rule needing a feature
/// the logic did not declare means the header would have been short, and it
/// usually means the problem's `(set-logic …)` is wrong.
fn report_logic(
    logic: Option<&str>,
    declared: Features,
    used: Features,
    kind: logic::LogicKind,
) {
    let name = logic.unwrap_or("(none)");
    if kind == logic::LogicKind::Unrecognised && logic.is_some() && logic != Some("ALL") {
        log::warn!("`{name}` is not one of the 25 SMT-LIB logics; assuming every theory");
    }
    let missing = used.difference(declared);
    if !missing.is_empty() {
        log::warn!(
            "proof uses {missing:?}, which `(set-logic {name})` does not declare; \
             the import list was widened to match"
        );
    }
    let unsupported = used.unsupported();
    if !unsupported.is_empty() {
        log::warn!("proof uses {unsupported:?}, which the Lambdapi backend does not implement");
    }
}
